version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-montink
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - montinknet

  web:
    image: nginx:stable
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - montinknet

  db:
    image: mariadb:10.6
    container_name: laravel-dbmontink
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp_montink
      MYSQL_USER: usermontink
      MYSQL_PASSWORD: laravelmontink
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - montinknet

  frontend:
    container_name: react-frontend-gosat
    build:
      context: ../erp_gerenciamento_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - montinknet

volumes:
  dbdata:

networks:
  montinknet:
    driver: bridge
